In [1]:
import numpy as np

# Numpy 
    - 수치해석용 파이썬 패키지 
    - nparray: 다차원 배열 자료구조 클래스 
    - 주로 백터와 행렬을 사용하는 선형대수 계산에 사용한다. 
        (백터화 연산을 통해 복잡한 선형대수 연산을 수행할 수 있다.)

In [2]:
ar = np.array([0,1,2,3,4,5,6,7,8,9]);ar

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
type(ar)

numpy.ndarray

In [4]:
data = [ 0,1,2,3,4,5,6,7,8,9]
answer = []
for di in data:
    answer.append(2*di)
answer

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [5]:
#벡터화 연산을 통해 for 반복문 없이 한번에 하기
x =np.array(data);2*x

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

# 2차원 배열 만들기 
    - ndarray :n dimentional array 
    - list of list 를 이용해 2차원 배열 생성

In [6]:
c=np.array([[0,1,2],[3,4,5]]);c

array([[0, 1, 2],
       [3, 4, 5]])

In [7]:
len(c) #행의 갯수

2

In [8]:
len(c[0]) #열의 갯수

3

In [ ]:
3차원 배열 만들기 
    - 2*3*4 array

In [13]:
d = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]],
              [[11, 12, 13, 14],
               [15, 16, 17, 18],
               [19, 20, 21, 22]]])
d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[11, 12, 13, 14],
        [15, 16, 17, 18],
        [19, 20, 21, 22]]])

In [14]:
#3차원 배열의 행, 열 , 깊이
len(d),len(d[0]),len(d[0][0])

(2, 3, 4)

# 배열의 차원과 크기 나타내기

In [15]:
# ndim : 배열의 차원
# shape: 배열의 크기 

a= np.array([1,2,3])
print(a.ndim)
print(a.shape)

1
(3,)


# 배열 인덱싱
        -Boolean 방식:True or False 로만 구성 됨 
        -정수 방식:원소 각각이 ndarray 객체 원소 하나를 가리키는 인덱스 정수 

In [16]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
idx = np.array([True, False, True, False, True,
                False, True, False, True, False])
a[idx]

array([0, 2, 4, 6, 8])

In [17]:
a%2==0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])